### ISSUE TITLE
Continous Random Erros

### ISSUE THREAD

**Issue by harshmandan** [dedo1911/socket.io-pm2#1]
Getting these random errors. I'm using pm2 with cluster mode for 2 nodejs instances.
```

TypeError: Cannot read property 'sock' of null
 at ReqSocket.connectHandler (/home/felb2bnode/live/felb2bnode/node_modules/pm2/lib/Client.js:363:17)
    at Object.onceWrapper (events.js:421:28)
       at ReqSocket.emit (events.js:327:22)
          at Socket.<anonymous> (/home/felb2bnode/live/felb2bnode/node_modules/pm2-axon/lib/sockets/sock.js:291:10)
             at Socket.emit (events.js:327:22)
                at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1127:10)
```

**Comment by dedo1911** [comment]
Are you sure this is related to this library? Are you able to share the slice of code you think might be causing this issue?

**Comment by dedo1911** [comment]
I'm closing this as not getting any updates. Please tell me if errors are still occurring.
